# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'ocorrência', 'verbose_name_plural': 'ocorrências'},
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('F', 'Foco'), ('C', 'Criadouro'), ('S', 'Suspeita')], max_length=1, verbose_name='categoria'),
        ),
    ]
