# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160326_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ('label',), 'verbose_name': 'centro de interesse', 'verbose_name_plural': 'centros de interesse'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-id',), 'verbose_name': 'ocorrência', 'verbose_name_plural': 'ocorrências'},
        ),
        migrations.AddField(
            model_name='cluster',
            name='address',
            field=models.CharField(blank=True, max_length=512, verbose_name='endereço'),
        ),
    ]
