# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160327_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='breeding_count',
            field=models.PositiveIntegerField(default=0, verbose_name='criadouros'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='focus_count',
            field=models.PositiveIntegerField(default=0, verbose_name='foco'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='suspicion_count',
            field=models.PositiveIntegerField(default=0, verbose_name='suspeita'),
        ),
    ]
