# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160329_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='foto'),
        ),
    ]
