# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160329_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='comentário'),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='resolvido'),
        ),
    ]
