# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160330_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('F', 'Foco'), ('C', 'Criadouro'), ('SD', 'Suspeita de dengue'), ('SZ', 'Suspeita de zika'), ('SC', 'Suspeita de chikungunya')], max_length=2, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='report',
            name='photo',
            field=models.ImageField(blank=True, upload_to='upload/%Y/%m/%d/', verbose_name='foto'),
        ),
    ]
